version: '3'
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: badpassword
      POSTGRES_DB: udm-server-apollo-db
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: